### ISSUE TITLE
possible to get the CAD files for the CV keyboard?

### ISSUE THREAD

**Issue by KeLaiFu** [brianhainsworth/CV_Keyboard_with_ADSR#1]
Thanks for making this euro module of the Ken stone original, I have had that on my to-do list forever and a day so I am SO happy to see you've done it already!
I was wondering if it was possible to share the kicad/eagle/whatever files you made for this? I'd like to play around with it.
The idea I was kicking around in my head when I saw the KS version was an 8hp IO module, with an additional keyboard module, either a second 8HP vertical style one, or a 1U horizontal one. 
Totally understand if you want to keep those to yourself though, I will be glad to make your version either way.

**Comment by brianhainsworth** [comment]
Heck, you are quick!! Its EasyEDA as I am new to all of this and I haven't figured anything else out yet. I'll try get something sorted for you in a bit

**Comment by brianhainsworth** [comment]
I've uploaded the EasyEDA files. I haven't used these files, imported or exported to EasyEDA before, so use them at your own risk. I cant imagine them not working though. Maybe double check them to the schematic image or something
