### ISSUE TITLE
appreaciated...but

### ISSUE THREAD

**Issue by KeLaiFu** [brianhainsworth/CV_Keyboard_with_ADSR#2]
I've uploaded the EasyEDA files. I haven't used these files, imported or exported to EasyEDA before, so use them at your own risk. I cant imagine them not working though. Maybe double check them to the schematic image or something

_Originally posted by @brianhainsworth in https://github.com/brianhainsworth/CV_Keyboard_with_ADSR/issues/1#issuecomment-1519325113_

The EasyEDA file is much appreciated...but at the moment I dont think the scm.json can be imported into kicad which is my weapon of choice at the moment, however I believe the other file easyeda makes (I i think it's 'filename.easyeda.json') can be, is it possible to add that one?

Sorry to be a pain in the butt!

**Comment by brianhainsworth** [comment]
No worries!

The only options I have to export out of EasyEDA is EasyEDA and Altium, Altium even gives some kind of weird warning as well so it might not work. I've exported the Altium files and added them if they are any use. My only other suggestion I can think of is to download EasyEDA, import them and then try exporting them to KiCAD yourself, that way you will know the settings and stuff that you need. I hope that helps, sorry if its not that helpful.

**Comment by KeLaiFu** [comment]
I think it depends on which mode you are in at the time of export, although I am pretty clueless. The file you upped initially was the schematic file, which doesnt include the PCB layout information. In my brief playing with easyeda files in kicad, I was only able to import a board layout and play around with that, which is fine for something like this where I dont want to make any adjustments to the actual workings of the circuit. I'll take a look into it again later, now I have to work..gah!

**Comment by brianhainsworth** [comment]
I hope you get something to work. When I was going over the files I realised that I hadn't uploaded the PCB export. I had it sitting here on my computer but it hadn't got here yet for some reason, its in there now though. Good luck, work sux

**Comment by KeLaiFu** [comment]
All good! Got the file into kicad, will try put my spin on things and all being well, I'll post the results on my github. Thanks again
